---
title: "bulk-deconvolution"
author: "unawaz1996"
date: "2023-09-24"
output:
  html_notebook: default
  workflowr::wflow_html:
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    autodep = TRUE,
    eval = TRUE,
	echo = FALSE,
	warning = FALSE,
	message = FALSE
)
```

# Background 

# Set-up
```{r}
source("code/preprocess/functions.R")
source("code/deconvolution/utility_functions.R")
source("code/deconvolution/fun-cibersort.R")
load(here::here("data/signatures/sigsBrain.rda"))
library(recount3)
library(magrittr)
library(tibble)
library(reshape2)
library(SummarizedExperiment)
library(corrplot)
library(dplyr)
library(ggvenn)
library(pander)
library(gridExtra)
library(variancePartition)
library(DT)
library(EnsDb.Hsapiens.v86)
library(singscore)
library(AnnotationHub)
library(stargazer)
library(ggfortify)
library(glue)
library(cowplot)
library(broom)
library(glmpca)
library(naniar)
library(DeconRNASeq)
library(dtangle)
library(e1071)
library(parallel)
library(preprocessCore)
library(Metrics)
library(DTWBI)
```


```{r}
load(file = here::here("output/Results/Deconvolution/decon-estimates.Rda"))
brain.dir =file.path("/home/neuro/Documents/BrainData/Bulk")
```



<!-- # ```{r load-data} -->
<!-- #  -->
<!-- # e <- list() -->
<!-- #    -->
<!-- # e$GTEx <- read.csv(file.path(brain.dir, "/GTEx/Formatted/GTEx-exp.csv"),  -->
<!-- #                        check.names = FALSE, row.names = 1) -->
<!-- # e$PE <- read.csv(file.path(brain.dir, "/PsychEncode/Formatted/PsychEncode-exp.csv"),  -->
<!-- #                      row.names =1, check.names = FALSE) -->
<!-- # e$BSpan <- read.csv(file.path(brain.dir, "/BrainSpan/Formatted/BrainSpan-exp.csv"), -->
<!-- #                         check.names = FALSE, row.names = 1) -->
<!-- # e$BSeq <- read.csv(file.path(brain.dir,"/Brainseq/Formatted/BrainSeq-exp.csv"),  -->
<!-- #                        check.names = FALSE, row.names = 1) -->
<!-- #  -->
<!-- # e$HDBR <- read.csv(file.path(brain.dir, "/HDBR/Formatted/HDBR-exp.csv"),  -->
<!-- #                        check.names = FALSE, row.names = 1)  %>%  -->
<!-- #   column_to_rownames("EnsemblID") -->
<!-- # ``` -->



```{r metadata-load}
md = list()
md$GTEx <- read.csv(file.path(brain.dir, "/GTEx/Formatted/GTEx-metadata.csv"), 
                       check.names = FALSE, row.names = 1)
md$PE <- read.csv(file.path(brain.dir,"/PsychEncode/Formatted/PsychEncode-metadata.csv"),
                  check.names = FALSE)
md$BSeq <- read.csv(file.path(brain.dir,"/Brainseq/Formatted/BrainSeq-metadata.csv"), 
                       check.names = FALSE)
md$HDBR <- read.csv(file.path(brain.dir, "/HDBR/Formatted/HDBR-metadata.csv"), 
                       check.names = FALSE, row.names = 1) 

md$BSpan <- read.csv(file.path(brain.dir,
                               "/BrainSpan/Formatted/BrainSpan-metadata.csv"),
                     check.names = FALSE)
  


```

# Analysis 

<!-- ## Goodness-of-fit -->


<!-- ```{r} -->

<!-- gof_results = list() -->

<!-- ## BrainSpan -->
<!-- gof_results$BSpan_DRS = write.gof(e$BSpan, decon_results$BSpan_DRS, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% -->
<!--   mutate(Dataset= "BrainSpan", -->
<!--          Deconvolution = "DeconRNASeq") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("X", "", SampleID)) %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$BSpan %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$BSpan_DTG = write.gof(e$BSpan, decon_results$BSpan_DTG, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "BrainSpan", -->
<!--                              Deconvolution = "Dtangle")  %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--    mutate(SampleID = gsub("X", "", SampleID)) %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$BSpan %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$BSpan_CBS = write.gof(e$BSpan, decon_results$BSpan_CIBERSORT, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "BrainSpan", -->
<!--                              Deconvolution = "Cibersort")  %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("X", "", SampleID)) %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$BSpan %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->



<!-- ## BrainSeq -->
<!-- gof_results$BSeq_DRS = write.gof(e$BSeq, decon_results$BSeq_DRS, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "BrainSeq", -->
<!--                              Deconvolution = "DeconRNASeq") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   left_join(md$BSeq %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$BSeq_DTG = write.gof(e$BSeq, decon_results$BSeq_DTG, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "BrainSeq", -->
<!--                              Deconvolution = "Dtangle") %>% -->
<!--   rownames_to_column("SampleID")  %>% -->
<!--   left_join(md$BSeq %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$BSeq_CBS = write.gof(e$BSeq, decon_results$BSeq_CIBERSORT, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "BrainSeq", -->
<!--                              Deconvolution = "Cibersort")%>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   left_join(md$BSeq %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->


<!-- ## GTEx -->
<!-- gof_results$GTEx_DRS = write.gof(e$GTEx, decon_results$GTEx_DRS, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "GTEx", -->
<!--                              Deconvolution = "DeconRNASeq")%>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID))  %>% -->
<!--   left_join(md$GTEx %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$GTEx_DTG = write.gof(e$GTEx, decon_results$GTEx_DTG, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "GTEx", -->
<!--                              Deconvolution = "Dtangle")%>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$GTEx %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$GTEx_CBS = write.gof(e$GTEx, decon_results$GTEx_CIBERSORT, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "GTEx", -->
<!--                              Deconvolution = "Cibersort") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$GTEx %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->


<!-- ## PsychEncode -->
<!-- gof_results$PE_DRS = write.gof(e$PE, decon_results$PE_DRS, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "PsychEncode", -->
<!--                              Deconvolution = "DeconRNASeq") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("X", "", SampleID), -->
<!--          SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$PE %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$PE_DTG = write.gof(e$PE, decon_results$PE_DTG, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "PsychEncode", -->
<!--                              Deconvolution = "Dtangle") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("X", "", SampleID), -->
<!--          SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$PE %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->


<!-- gof_results$PE_CBS = write.gof(e$PE, decon_results$PE_CIBERSORT, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "PsychEncode", -->
<!--                              Deconvolution = "Cibersort") %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   mutate(SampleID = gsub("X", "", SampleID), -->
<!--          SampleID = gsub("\\.", "-", SampleID)) %>% -->
<!--   left_join(md$PE %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- ## HDBR -->
<!-- gof_results$HDBR_DRS = write.gof(e$HDBR, decon_results$HDBR_DRS, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "HDBR", -->
<!--                              Deconvolution = "DeconRNASeq") %>% -->
<!--   rownames_to_column("SampleID")  %>% -->
<!--   left_join(md$HDBR %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$HDBR_DTG = write.gof(e$HDBR, decon_results$HDBR_DTG, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "HDBR", -->
<!--                              Deconvolution = "Dtangle") %>% -->
<!--   rownames_to_column("SampleID")  %>% -->
<!--   left_join(md$HDBR %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->

<!-- gof_results$HDBR_CBS = write.gof(e$HDBR, decon_results$HDBR_CIBERSORT, sigsBrain$MB) %>% -->
<!--   as.data.frame() %>% mutate(Dataset= "HDBR", -->
<!--                              Deconvolution = "Cibersort") %>% -->
<!--   rownames_to_column("SampleID")   %>% -->
<!--   left_join(md$HDBR %>% -->
<!--               dplyr::select(SampleID, Regions, Period), by = "SampleID") -->
<!-- ``` -->

<!-- - Overall -->

<!-- ```{r} -->
<!-- overall = do.call(rbind, gof_results) %>% -->
<!--   ggplot(aes(y = r, x = Deconvolution, fill = Deconvolution)) + -->
<!--   geom_violin( alpha = 0.75) + -->
<!--       geom_boxplot(width=0.1)+ facet_grid(~Dataset) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_blank(), -->
<!--         legend.position = "top", -->
<!--         axis.title.x = element_blank(), -->
<!--         axis.text.y = element_text(size = 12), -->
<!--         axis.title.y = element_text(size = 15), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank()) + -->
<!--   geom_hline(yintercept = c(0.5,0.7), color = "black",linetype='dotted') + -->
<!--   ylab("Goodness of fit (r)") + -->
<!--   scale_fill_manual(values = -->
<!--                       c("Cibersort" = "#fdaf91", -->
<!--                         "DeconRNASeq" = "#ad002b", -->
<!--                         "Dtangle" = "#925e9f")) -->

<!-- overall -->
<!-- ggsave(plot = overall, -->
<!--        filename = here::here("output/Thesis_plots/Deconvolution/GoF-overall.svg"), -->
<!--        height = 4, -->
<!--        width = 7.31, -->
<!--        units = "in") -->
<!-- ``` -->



<!-- - Across developmental periods -->
<!-- ```{r} -->
<!-- period_gof = do.call(rbind, gof_results) %>% -->
<!--   drop_na(Period) %>% -->
<!--   mutate(Period = factor(Period, levels = c("Prenatal", "Postnatal"))) %>% -->
<!--   ggplot(aes(y = r, x = Deconvolution, fill = Deconvolution)) + -->
<!--   geom_violin( alpha = 0.75) + -->
<!--       geom_boxplot(width=0.1)+ facet_grid(Dataset~Period) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_blank(), -->
<!--         legend.position = "top", -->
<!--         axis.title.x = element_blank(), -->
<!--         axis.text.y = element_text(size = 12), -->
<!--         axis.title.y = element_text(size = 15), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank()) + -->
<!--   geom_hline(yintercept = c(0.5,0.7), color = "black",linetype='dotted') + -->
<!--   ylab("Goodness of fit (r)") + -->
<!--   scale_fill_manual(values = -->
<!--                       c("Cibersort" = "#fdaf91", -->
<!--                         "DeconRNASeq" = "#ad002b", -->
<!--                         "Dtangle" = "#925e9f")) -->

<!-- period_gof -->

<!-- ggsave(plot = period_gof, -->
<!--        filename = here::here("output/Thesis_plots/Deconvolution/GoF-period.svg"), -->
<!--        height = 9.30, -->
<!--        width = 8.15, -->
<!--        units = "in") -->
<!-- ``` -->

<!-- - Across regions -->

<!-- ```{r} -->

<!-- dodge <- position_dodge(width = 0.8) -->
<!-- regions = do.call(rbind, gof_results) %>% -->
<!--   drop_na(Period) %>% -->
<!--   ggplot(aes(y = r, x = Deconvolution, fill = Regions)) + -->
<!--   geom_boxplot() + -->
<!--  # -->
<!--   facet_grid(Dataset~Deconvolution, scales = "free_x") + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_blank(), -->
<!--         legend.position = "top", -->
<!--         axis.title.x = element_blank(), -->
<!--         axis.text.y = element_text(size = 12), -->
<!--         axis.title.y = element_text(size = 15), -->
<!--         panel.grid.major = element_blank(), -->
<!--         panel.grid.minor = element_blank()) + -->
<!--   geom_hline(yintercept = c(0.5,0.7), color = "black",linetype='dotted') + -->
<!--   ylab("Goodness of fit (r)") + -->
<!--     scale_fill_manual(values = c("Cortex" = "#E85571", -->
<!--                                  "Subcortex" = "#838DE0", -->
<!--                                  "Cerebellum" = "#FFD256", -->
<!--                                  "Spinal Cord" = "#C6D14A", -->
<!--                                  "Forebrain" = "#F6B19D", # -->
<!--                                  "Midbrain" = "#AC93AD", -->
<!--                                  "Hindbrain" = "#6E8B8E", -->
<!--                                  "Brain" = "#FFA6B7", -->
<!--                                  "Forebrain and midbrain" = "#9D696C" -->
<!--                                 )) -->


<!-- ggsave(plot = regions, -->
<!--        filename = here::here("output/Thesis_plots/Deconvolution/GoF-regions.svg"), -->
<!--        height = 9.30, -->
<!--        width = 7.31, -->
<!--        units = "in") -->
<!-- ``` -->


<!-- ## Proportion estimation -->

<!-- - BrainSeq -->

<!-- ```{r} -->
<!-- decon_bseq =decon_results$BSeq_CIBERSORT %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSeq) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- decon_results$BSeq_DRS %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSeq) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$BSeq_DTG %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSeq) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- - BrainSpan -->

<!-- ```{r} -->
<!-- decon_bspan = decon_results$BSpan_CIBERSORT %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSpan) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$BSpan_DRS %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSpan) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$BSpan_DTG %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$BSpan) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->


<!-- - GTEx -->

<!-- ```{r} -->
<!-- decon_results$GTEx_CIBERSORT %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$GTEx) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$GTEx_DRS %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$GTEx) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$GTEx_DTG %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$GTEx) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- - HDBR -->

<!-- ```{r} -->
<!-- decon_results$HDBR_CIBERSORT %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$HDBR) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("")+ -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$HDBR_DRS %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$HDBR) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("")+ -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$HDBR_DTG %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$HDBR) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- - PsychEncode -->

<!-- ```{r} -->
<!-- decon_results$PE_CIBERSORT %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$PE) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$PE_DRS %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$PE) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

<!-- ```{r} -->
<!-- decon_results$PE_DTG %>% -->
<!--   as.data.frame %>% -->
<!--   rownames_to_column("SampleID") %>% -->
<!--   dplyr::select(SampleID, Neurons, Astrocytes, -->
<!--                 Oligodendrocytes, Microglia, Endothelia) %>% -->
<!--   melt() %>% -->
<!--   left_join(md$PE) %>% -->
<!--   drop_na(Regions) %>% -->
<!--   mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", -->
<!--                                               "Oligodendrocytes", -->
<!--                                               "Astrocytes", -->
<!--                                               "Neurons")), -->
<!--          Regions = factor(Regions, levels = c("Cortex", "Subcortex", -->
<!--                                               "Cerebellum", "Spinal Cord") )) %>% -->
<!--   ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() + -->
<!--   #scale_fill_manual(values = c("Cortex" = "#E85772", -->
<!--    #                                          "Subcortex" = "#878DC5", -->
<!--     #                                        "Cerebellum" = "#FFD357", -->
<!--      #                                        "Spinal Cord" = "#C6D14A")) + -->
<!--   theme_bw() + -->
<!--   theme(axis.text.x = element_text(size = 10), -->
<!--         axis.text.y = element_text(size = 10), -->
<!--         legend.position = "none") + coord_flip() + -->
<!--   facet_grid(~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") + -->
<!--   scale_fill_manual(values = c("Neurons" = "#D94A70", -->
<!--                                "Astrocytes" = "#5590CC", -->
<!--                                "Oligodendrocytes" = "#AF9DCB", -->
<!--                                "Microglia" = "#69C9CF", -->
<!--                                "Endothelia" = "#FAE47B")) -->

<!-- ``` -->

```{r}
pe.cbs  = decon_results$PE_CIBERSORT %>% 
  as.data.frame() %>%
  mutate(Dataset = "PsychEncode") %>% 
  rownames_to_column("SampleID") %>% 
  dplyr::select(SampleID, Neurons, Astrocytes,
                Oligodendrocytes, Microglia, Endothelia, Dataset) %>%
  left_join(md$PE %>% 
              dplyr::select(SampleID, Regions, Period, AgeInterval), by = "SampleID")


gtex.cbs = decon_results$GTEx_CIBERSORT %>% 
  as.data.frame() %>%
  mutate(Dataset = "GTEx") %>% 
  rownames_to_column("SampleID") %>%
  dplyr::select(SampleID, Neurons, Astrocytes,
                Oligodendrocytes, Microglia, Endothelia, Dataset) %>%
  left_join(md$GTEx %>% 
              dplyr::select(SampleID, Regions, Period, AgeInterval), by = "SampleID")

hdbr.cbs = decon_results$HDBR_CIBERSORT %>% 
  as.data.frame() %>%
  mutate(Dataset = "HDBR") %>% 
  rownames_to_column("SampleID") %>% 
  dplyr::select(SampleID, Neurons, Astrocytes,
                Oligodendrocytes, Microglia, Endothelia, Dataset) %>%
  left_join(md$HDBR %>% 
              dplyr::select(SampleID, Regions, Period, AgeInterval), by = "SampleID")

bseq.cbs = decon_results$BSeq_CIBERSORT %>% 
  as.data.frame() %>%
  mutate(Dataset = "BrainSeq") %>% 
  
  rownames_to_column("SampleID") %>% 
  dplyr::select(SampleID, Neurons, Astrocytes,
                Oligodendrocytes, Microglia, Endothelia, Dataset) %>%
  left_join(md$BSeq%>% 
              dplyr::select(SampleID, Regions, Period, AgeInterval), by = "SampleID")
bspan.csb = decon_results$BSpan_CIBERSORT%>% 
  as.data.frame() %>%
  mutate(Dataset = "BrainSpan") %>% 
  rownames_to_column("SampleID") %>% 
  dplyr::select(SampleID, Neurons, Astrocytes,
                Oligodendrocytes, Microglia, Endothelia, Dataset) %>%
  left_join(md$BSpan %>% 
              dplyr::select(SampleID, Regions, Period, AgeInterval), by = "SampleID") 


cibersort_all = rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      hdbr.cbs, 
      gtex.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
  dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", 
                                              "Oligodendrocytes", 
                                              "Astrocytes", 
                                              "Neurons")),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Chroid plexus", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord") )) %>% 
  ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + coord_flip() + 
  facet_grid(Dataset~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Neurons" = "#D94A70", 
                               "Astrocytes" = "#5590CC", 
                               "Oligodendrocytes" = "#AF9DCB", 
                               "Microglia" = "#69C9CF", 
                               "Endothelia" = "#FAE47B")) #+
cibersort_all
#facet_wrap(Dataset~Regions)


cibersort_hdbr = rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      hdbr.cbs, 
      gtex.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
  dplyr::filter(Dataset == "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Endothelia", "Microglia", 
                                              "Oligodendrocytes", 
                                              "Astrocytes", 
                                              "Neurons")),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Chroid plexus", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord") )) %>% 
  ggplot(aes(x = variable, y = value, fill = variable)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + coord_flip() + 
  facet_grid(Dataset~Regions, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Neurons" = "#D94A70", 
                               "Astrocytes" = "#5590CC", 
                               "Oligodendrocytes" = "#AF9DCB", 
                               "Microglia" = "#69C9CF", 
                               "Endothelia" = "#FAE47B"))

cibersort_hdbr 
ggsave(plot = cibersort_all, 
       filename = here::here("output/Thesis_plots/Deconvolution/cibersort-estimates-all.svg"), 
       height = 9.30, 
       width = 10.55, 
       units = "in")

ggsave(plot = cibersort_hdbr, 
       filename = here::here("output/Thesis_plots/Deconvolution/cibersort-estimates-hdbr.svg"), 
       height = 3.07, 
       width = 10.55, 
       units = "in")
```

- Across age intervals and regions 

```{r}
bseq.cbs %>% 
  melt() %>%
  mutate(AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>%
  ggplot(aes(x = AgeInterval,y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + facet_grid(~variable) 

```

```{r}
bspan.csb %>% 
  melt() %>%
  mutate(AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>%
  ggplot(aes(x = AgeInterval,y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10, angle = 90),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + facet_grid(~variable) 

```


```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(variable == "Neurons") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(Dataset~variable, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))


```

```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(variable == "Astrocytes") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(Dataset~variable, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))


```


```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(variable == "Microglia") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(Dataset~variable, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```

```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(variable == "Endothelia") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(Dataset~variable, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```

```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(variable == "Oligodendrocytes") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(Dataset~variable, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```

## Datasets 

```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(Dataset == "BrainSeq") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(variable~Dataset, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```



```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(Dataset == "BrainSpan") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(variable~Dataset, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```

```{r fig.height=12, fig.width=20}
 rbind(pe.cbs,
      bspan.csb,
      bseq.cbs, 
      gtex.cbs, 
      hdbr.cbs) %>% 
  as.data.frame %>%
  melt() %>%
  drop_na(Regions) %>%
 # dplyr::filter(Dataset != "HDBR") %>%
  mutate(variable= factor(variable, levels = c("Neurons","Astrocytes", 
                                               "Endothelia", "Oligodendrocytes",
                                               "Microglia"
                                              
                                              )),
        Regions = factor(Regions, 
                         levels = c("Brain", "Forebrain","Hindbrain",
                                    "Midbrain", "Forebrain and midbrain", 
                                    "Cortex", "Subcortex",
                                    "Cerebellum", "Spinal Cord")),
        AgeInterval = factor(AgeInterval, levels = c("4-7pcw", "8-9pcw",
                                                        "10-12pcw", "13-15pcw", "16-18pcw",
                                                        "19-24pcw", "25-38pcw", "0-5mos",
                                                        "6-18mos", "19mos-5yrs", "6-11yrs",
                                                        "12-19yrs", "20-29yrs", "30-39yrs",
                                                      "40-49yrs", "50-59yrs", "60-69yrs",
                                                      "70-79yrs", "80-89yrs", "90-99yrs"))) %>% 
  dplyr::filter(Dataset == "PsychEncode") %>%
  ggplot(aes(x = AgeInterval, y = value, fill = Regions)) + geom_boxplot() +
  theme_bw() +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 12), 
        legend.position = "none") + 
  facet_grid(variable~Dataset, scales = "free") +ylab("Estimated Proportion") + xlab("") +
  scale_fill_manual(values = c("Cortex" = "#E85571", 
                                 "Subcortex" = "#838DE0", 
                                 "Cerebellum" = "#FFD256",
                                 "Spinal Cord" = "#C6D14A", 
                                 "Forebrain" = "#F6B19D", #
                                 "Midbrain" = "#AC93AD",
                                 "Hindbrain" = "#6E8B8E",
                                 "Brain" = "#FFA6B7", 
                                 "Forebrain and midbrain" = "#9D696C"
                                ))

```

## Export the datasets 

```{r}


```
