---
title: "isoform-exp"
author: "urwahnawaz"
date: "2023-10-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(CePa)
library(EnsDb.Hsapiens.v86)
library(recount3)
library(DT)
library(dplyr)
library(tidyr)
source("code/preprocess/functions.R")
source("code/deconvolution/utility_functions.R")
library(pander)
library(gridExtra)
library(variancePartition)
library(corrplot)
library(edgeR)
library(pheatmap)
library(viridis)


txdf = transcripts(EnsDb.Hsapiens.v86, return.type="DataFrame")
tx2gene = as.data.frame(txdf[,c("gene_id", "tx_id")])

```

```{r}
gtex_trans = read.gct("/home/neuro/Documents/BrainData/Bulk/GTEx/GTEx_Analysis_2017-06-05_v8_RSEMv1.3.0_transcript_tpm.gct.gz")
colnames(gtex_trans ) <- gsub("\\.", "-", colnames(gtex_trans))


```


```{r}
dir = file.path("/home/neuro/Documents/BrainData/Bulk/GTEx/")
annot= read.csv(here::here("data/annotations/GTEx-metadata-annot.csv"))
attributes = list.files(dir, full.names = TRUE, pattern = "\\SampleAttributesDS.txt") # Sample attributes contains sample level information
phenotype = list.files(dir, full.names = TRUE, pattern = "\\SubjectPhenotypesDS.txt")
md = read_tsv(attributes, col_types = c('.default' = 'c')) %>% 
    #filter(SMTS == 'Brain') %>% 
    mutate(SUBJID = sapply(str_split(SAMPID, pattern = "-"), function(x) paste(x[1:2], collapse = '-'))) %>%
    left_join(read_tsv(phenotype, col_types = c('.default' = 'c')))  %>% as.data.frame()
colnames(md) = annot$BITColumnName[match(colnames(md), annot$OriginalMetadataColumnName)]
```

```{r}
gtex_trans = gtex_trans %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(contains(md$SampleID))
```

```{r}
a = with(md, setNames(StructureAcronym, SampleID))[names(gtex_trans)[col(gtex_trans)]]
#a <- with(md, setNames(StructureAcronym, SampleID))[names(gtex_trans_update)[col(gtex_trans_update)]]
tapply(unlist(gtex_trans), list(row(gtex_trans), a), mean)
```


## For ZMYND8 and FMR1 

```{r}
palette = colorRampPalette(c("#2F124B", "#6E74B4","#F9F9F9", "#FD9675", "#EA2A5F"))(100)
zmynd8_heatmap_gtex = gtex_trans %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000101040") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(md$SampleID))

dim(zmynd8_heatmap)

#StructureAcronym


average = with(md, setNames(StructureAcronym, SampleID))[names(zmynd8_heatmap_gtex)[col(zmynd8_heatmap_GTEx)]]

average_exp = tapply(unlist(zmynd8_heatmap_gtex), list(row(zmynd8_heatmap_gtex), average ), mean)

rownames(average_exp) = rownames(zmynd8_heatmap_gtex)

order_zmynd8 = rownames(average_exp)

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, 
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, border_color = "grey", 
         color= palette)


a <- with(df_category, setNames(Category, Col_name))[names(df)[col(df)]]
tapply(unlist(df), list(row(df), a), mean)
```


```{r}

#palette <- colorRampPalette(c("#10c1e5", "#82e0b4",
 #                             "#F9F9F9", "#FBB829", "#FF0066"))(100)


FMR1_heatmap = gtex_trans %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000102081") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(md$SampleID))

dim(FMR1_heatmap)

#StructureAcronym


average = with(md, setNames(StructureAcronym,SampleID))[names(FMR1_heatmap)[col(FMR1_heatmap)]]

average_exp = tapply(unlist(FMR1_heatmap), list(row(FMR1_heatmap), average ), mean)

rownames(average_exp) = rownames(FMR1_heatmap)


pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)


a <- with(df_category, setNames(Category, Col_name))[names(df)[col(df)]]
tapply(unlist(df), list(row(df), a), mean)
```


### UPF3B


```{r}
palette = colorRampPalette(c("#2F124B", "#6E74B4","#F9F9F9", "#FD9675", "#EA2A5F"))(100)
zmynd8_heatmap_gtex = gtex_trans %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000125351") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(md$SampleID))

dim(zmynd8_heatmap)

#StructureAcronym


average = with(md, setNames(StructureAcronym, SampleID))[names(zmynd8_heatmap_gtex)[col(zmynd8_heatmap_GTEx)]]

average_exp = tapply(unlist(zmynd8_heatmap_gtex), list(row(zmynd8_heatmap_gtex), average ), mean)

rownames(average_exp) = rownames(zmynd8_heatmap_gtex)


tx_order = c("ENST00000345865",  "ENST00000636792", "ENST00000276201", "ENST00000619445", "ENST00000478840")
average_exp = average_exp[match(tx_order , rownames(average_exp)), ]


pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, 
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, border_color = "grey", 
         color= palette)


a <- with(df_category, setNames(Category, Col_name))[names(df)[col(df)]]
tapply(unlist(df), list(row(df), a), mean)
```


## Across development using Brainseq

```{r}
dir = file.path("/home/neuro/Documents/BrainData/Bulk")
bseq = file.path(dir, "Brainseq")
bseq.md = read.csv(file.path(dir, "Brainseq/Formatted/BrainSeq-metadata.csv"), 
                   header=TRUE) %>%
  mutate(Age_rounded = as.character(sapply(na.omit(.$AgeNumeric), num_to_round)))
load(file.path(bseq, "rse_tx_unfiltered.Rdata"), envir = .GlobalEnv)

exp = rse_tx@assays@.xData$data$tpm %>%
  as.data.frame() %>% 
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>%
  column_to_rownames("tx_id")

```

```{r}
hip_samples = bseq.md %>%
  dplyr::filter(StructureAcronym == "HIP")

hip_exp = exp %>%
  as.data.frame() %>%
  dplyr::select(contains(hip_samples$SampleID))


pfc_samples = bseq.md %>%
  as.data.frame() %>%
  dplyr::filter(StructureAcronym == "DLPFC")

pfc_exp = exp %>%
  as.data.frame()%>%
  dplyr::select(contains(pfc_samples$SampleID)) 
```


## ZMYND8

Average all data 
```{r}

average = with(bseq.md, setNames(AgeInterval,SampleID))[names(exp)[col(exp)]]

average_exp = tapply(unlist(exp), list(row(exp), average ), mean)

rownames(average_exp) = rownames(exp)

write.csv(average_exp, "/home/neuro/Documents/BrainData/Bulk/Brainseq/Formatted/BrainSeq-tx-exp.csv")
```


```{r}
average = with(hip_samples, setNames(AgeInterval,SampleID))[names(hip_exp)[col(hip_exp)]]

average_exp = tapply(unlist(hip_exp), list(row(hip_exp), average ), mean)

rownames(average_exp) = rownames(hip_exp)

write.csv(average_exp, "/home/neuro/Documents/BrainData/Bulk/Brainseq/Formatted/BrainSeq-tx-hip-exp.csv")

```

```{r}
average = with(pfc_samples, setNames(AgeInterval,SampleID))[names(pfc_exp)[col(pfc_exp)]]

average_exp = tapply(unlist(pfc_exp), list(row(pfc_exp), average ), mean)

rownames(average_exp) = rownames(pfc_exp)

write.csv(average_exp, "/home/neuro/Documents/BrainData/Bulk/Brainseq/Formatted/BrainSeq-tx-pfc-exp.csv")


```

```{r}
tx_order = c("ENST00000619049", "ENST00000360911", "ENST00000536340","ENST00000617418",
             "ENST00000262975", "ENST00000458360", "ENST00000471951", "ENST00000467200",
             "ENST00000352431", "ENST00000461685", "ENST00000446994", "ENST00000435836",
             "ENST00000540497", "ENST00000355972", "ENST00000396281", "ENST00000311275", 
             "ENST00000441977", "ENST00000446894", "ENST00000372023", "ENST00000468376", 
             "ENST00000611941")
```

- Age Interval

```{r}
zmynd8_heatmap  = exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000101040") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(bseq.md$SampleID))

dim(zmynd8_heatmap)

#StructureAcronym



average = with(bseq.md, setNames(AgeInterval,SampleID))[names(zmynd8_heatmap)[col(zmynd8_heatmap)]]

average_exp = tapply(unlist(zmynd8_heatmap), list(row(zmynd8_heatmap), average ), mean)
rownames(average_exp) = rownames(zmynd8_heatmap)
average_exp %<>% 
  as.data.frame() %>%
  dplyr::select("13-15pcw", 
                "16-18pcw", 
                "19-24pcw", 
                "0-5mos", 
                "6-18mos", 
                "19mos-5yrs", 
                "6-11yrs", 
                "12-19yrs", 
                everything()) %>%
  as.matrix()
pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)

```

- Age Numeric 

```{r}

average = with(bseq.md, setNames(Age_rounded,SampleID))[names(zmynd8_heatmap)[col(zmynd8_heatmap)]]

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()
average_exp = tapply(unlist(zmynd8_heatmap), list(row(zmynd8_heatmap), average ), mean)
rownames(average_exp) = rownames(zmynd8_heatmap)

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)
```


- DLPFC 

```{r}
zmynd8_heatmap  = pfc_exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000101040") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(pfc_samples$SampleID))


average = with(pfc_samples, setNames(AgeInterval,SampleID))[names(zmynd8_heatmap)[col(zmynd8_heatmap)]]

average_exp = tapply(unlist(zmynd8_heatmap), list(row(zmynd8_heatmap), average ), mean)
rownames(average_exp) = rownames(zmynd8_heatmap)

average_exp = average_exp[match(tx_order , rownames(average_exp)), ]

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = FALSE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)
```

- Hippocampus 
```{r}
zmynd8_heatmap  = hip_exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000101040") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(hip_samples$SampleID))



average = with(hip_samples, setNames(AgeInterval,SampleID))[names(zmynd8_heatmap)[col(zmynd8_heatmap)]]

average_exp = tapply(unlist(zmynd8_heatmap), list(row(zmynd8_heatmap), average ), mean)
rownames(average_exp) = rownames(zmynd8_heatmap)

average_exp = average_exp[match(tx_order , rownames(average_exp)), ]

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = FALSE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)
```


## UPF3B

```{r}
upf3b_heatmap  = pfc_exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000125351") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(pfc_samples$SampleID))


average = with(pfc_samples, setNames(AgeInterval,SampleID))[names(upf3b_heatmap)[col(upf3b_heatmap)]]

average_exp = tapply(unlist(upf3b_heatmap), list(row(upf3b_heatmap), average ), mean)
rownames(average_exp) = rownames(upf3b_heatmap)


tx_order = c("ENST00000345865",  "ENST00000636792", "ENST00000276201", "ENST00000619445", "ENST00000478840")
average_exp = average_exp[match(tx_order , rownames(average_exp)), ]

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = FALSE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette, breaks = seq(-1, 1, length.out=100))

ggsave(filename = here::here("output/Thesis_plots/Examples/NDDs/UPF3B-DLFPC.svg"), height = 8, width =18)
```


```{r}
upf3b_heatmap  = hip_exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000125351") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(hip_samples$SampleID))


average = with(hip_samples, setNames(AgeInterval,SampleID))[names(upf3b_heatmap)[col(upf3b_heatmap)]]

average_exp = tapply(unlist(upf3b_heatmap), list(row(upf3b_heatmap), average ), mean)
rownames(average_exp) = rownames(upf3b_heatmap)

average_exp = average_exp[match(tx_order , rownames(average_exp)), ]

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = FALSE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette, breaks = seq(-1, 1, length.out=100))

ggsave(filename = here::here("output/Thesis_plots/Examples/NDDs/UPF3B-HIP.svg"), height = 8, width =18)
```


## FMR1

- Age Interval 

```{r}
FMR1_heatmap = exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000102081") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(bseq.md$SampleID))

dim(FMR1_heatmap)

#StructureAcronym


average = with(bseq.md, setNames(AgeInterval,SampleID))[names(FMR1_heatmap)[col(FMR1_heatmap)]]

average_exp = tapply(unlist(FMR1_heatmap), list(row(FMR1_heatmap), average ), mean)



rownames(average_exp) = rownames(FMR1_heatmap)



average_exp %<>% 
  as.data.frame() %>%
  dplyr::select("13-15pcw", 
                "16-18pcw", 
                "19-24pcw", 
                "0-5mos", 
                "6-18mos", 
                "19mos-5yrs", 
                "6-11yrs", 
                "12-19yrs", 
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)
```

- Age Numeric 

```{r}
average = with(bseq.md, setNames(Age_rounded,SampleID))[names(FMR1_heatmap)[col(FMR1_heatmap)]]

average_exp = tapply(unlist(FMR1_heatmap), list(row(FMR1_heatmap), average ), mean)

rownames(average_exp) = rownames(FMR1_heatmap)

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)

```

- PFC 

```{r}
FMR1_heatmap  = pfc_exp %>%
  as.data.frame() %>%
  rownames_to_column("tx_id") %>%
  mutate_at(.vars = "tx_id", .funs = gsub, pattern = "\\.[0-9]*$", replacement = "") %>% 
  left_join(tx2gene, by ="tx_id") %>% 
  dplyr::filter(gene_id == "ENSG00000102081") %>% 
  column_to_rownames("tx_id") %>% 
  dplyr::select(-gene_id) %>% 
  dplyr::select(contains(pfc_samples$SampleID))


average = with(pfc_samples, setNames(AgeInterval,SampleID))[names(FMR1_heatmap)[col(FMR1_heatmap)]]

average_exp = tapply(unlist(FMR1_heatmap), list(row(FMR1_heatmap), average ), mean)
rownames(average_exp) = rownames(FMR1_heatmap)

average_exp %<>% 
  as.data.frame() %>%
  dplyr::select(contains("pcw"),contains("mos"),
                everything()) %>%
  as.matrix()

pheatmap(log(average_exp + 0.05), scale = "none", cluster_rows = TRUE, border_color = "grey",
         cluster_cols= FALSE,cellwidth = 10, cellheight = 10, 
         color = palette)
```
